Repository bigismols/NUSMusollahFinder, pull requests merged in 2024-06, with the labels that each got.

#8 Implemented google autocomplete at HomeScreen
  .env
  App.js
  babel.config.js
  package-lock.json
  package.json
  screens/HomeScreen.js
  screens/LoginScreen.js
  slices/navSlice.js
Labels: enhancement

#9 Implemented a bit of mapscreen
  components/Map.js
  package-lock.json
  package.json
  screens/HomeScreen.js
  screens/MapScreen.js
Labels: bug, enhancement

#12 Edited UI heavily, no more Google Autocomplete
  %ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
  .env
  app.json
  components/Map.js
  package-lock.json
  package.json
  screens/HomeScreen.js
  screens/LoginScreen.js
  screens/MapScreen.js
  screens/SignupScreen.js
  slices/navSlice.js
  store.js
Labels: bug, enhancement

#13 Now current user location is tracked
  components/Map.js
  screens/HomeScreen.js
  slices/navSlice.js
Labels: enhancement

#15 Zoom to origin and proper location tracking done
  components/Map.js
  package-lock.json
  package.json
  slices/navSlice.js
Labels: bug, enhancement, help wanted

#17 added firebase.js file, edited login page
  firebase.js
  package-lock.json
  package.json
  screens/LoginScreen.js
Labels: enhancement

#18 Input Musollah location into DB and on map
  components/Map.js
  firebase.js
  package-lock.json
  package.json
  screens/LoginScreen.js
Labels: enhancement
